spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jesse-rr/bedding-bee-configs.git
          clone-on-start: true

server:
  port: 8888
